# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:22-alpine
ARG VERSION=latest
RUN addgroup -S mcp && adduser -S mcp -G mcp
RUN npm install -g mcp-proxy mongodb-mcp-server@${VERSION}
USER mcp
WORKDIR /home/mcp
CMD npx mcp-proxy --port ${PORT:-10000} mongodb-mcp-server
LABEL maintainer="MongoDB Inc <info@mongodb.com>"
LABEL description="MongoDB MCP Server"
LABEL version=${VERSION}
